### ISSUE TITLE
Write quick summary on how to use Twitter API

### ISSUE THREAD

**Issue by dsawali** [dsawali/tweetgrab#1]

**Comment by wilhans** [comment]
Sending an API call to Twitter requires:
**- oauth_consumer_key**
This is from the Twitter Apps.
**- oauth_nonce**
This is random base 64 characters.
**- oauth_signature**
This needs to be generated once before any request.
To generate oauth_signature, we need all of the OAuth variable (oauth_consumer_key, nonce, etc, except oauth_signature) that used to send the API plus consumer_key_secret and access_token_secret.
**- oauth_signature_method**
HMAC-SHA1
**- oauth_timestamp**
This needs to be generated once before any request.
(Generated using current time?)
**- oauth_token**
This is generated in Twitter Apps. (?)
**- oauth_version**
Usually 1.0 (I believe we can use 2.0? since we didn't use the write access? need to research more)

**Using Twurl to authorize:**
`twurl authorize --consumer-key consumer_key --consumer-secret consumer secret`
This command gives a URL for authorizing the app

**Twurl command to post to your timeline:**
`twurl -d 'status=any_string_for_status' /1.1/statuses/update.json`

**Twurl command to get tweets from your timeline:**
`twurl /1.1/statuses/home_timeline.json `

**Twurl command to search tweets:**
`twurl /1.1/search/tweets.json?q=query&result_type=popular/recent`

**Questions:**
Using OAuth 2.0?
Why is the oauth_token generated from twurl is different than the one on apps?
(is twurl generate the token?)

**References:**
https://github.com/twitter/twurl
https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets.html
https://developer.twitter.com/en/docs/basics/authentication/guides/authorizing-a-request.html

**Comment by wilhans** [comment]
We ended up using Twitter from NPM library to authorize the API call.
This library requires oauth_consumer_key, oauth_consumer_key_secret, oauth_access_token, and oauth_access_token_secret to authorize the call.

**References:**
https://github.com/desmondmorris/node-twitter
https://www.npmjs.com/package/twitter
